app.name=School Enrollment Management System
app.version=1.0.0
app.environment=development

db.url=jdbc:postgresql://localhost:5432/school_enrollment
db.username=postgres
db.password=136761090165Carl

logging.level=INFO

# Test database
test.db.url=jdbc:postgresql://localhost:5432/school_enrollment_test
test.db.username=postgres
test.db.password=136761090165Carl